version: '3'

services:
  api:
    build:
      context: .
      args:
        DB_URL: "postgres://admin:admin@db/api"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
