version: '3'

services:
  api:
    build:
      context: $PWD/api/
      dockerfile: $PWD/api/Dockerfile
      args:
        DB_URL: "postgres://admin:admin@db/api"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
  web:
    build:
      context: $PWD/web/
      dockerfile: $PWD/web/Dockerfile
      args:
        API_HOST: "http://api:8080"
    ports:
      - "5000:5000"
    depends_on:
      - api
